
FROM node:20-alpine

WORKDIR /app

# Install deps first (cached layer)
COPY package.json package-lock.json ./
COPY ./node_modules ./node_modules

# Copy source code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]

